/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jayson_jni_windows_NativeMethods */

#ifndef _Included_com_jayson_jni_windows_NativeMethods
#define _Included_com_jayson_jni_windows_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jayson_jni_windows_NativeMethods
 * Method:    HelloWorldStatic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jayson_jni_windows_NativeMethods_HelloWorldStatic
  (JNIEnv *, jclass);

/*
 * Class:     com_jayson_jni_windows_NativeMethods
 * Method:    HelloWorldDynamic
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jayson_jni_windows_NativeMethods_HelloWorldDynamic
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
